// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/LuckyKuang/sub2api-plus/ent/federationusagecursor"
)

// FederationUsageCursor is the model entity for the FederationUsageCursor schema.
type FederationUsageCursor struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope string `json:"scope,omitempty"`
	// LastDeliveredID holds the value of the "last_delivered_id" field.
	LastDeliveredID int64 `json:"last_delivered_id,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// NextRetryAt holds the value of the "next_retry_at" field.
	NextRetryAt  *time.Time `json:"next_retry_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FederationUsageCursor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case federationusagecursor.FieldID, federationusagecursor.FieldLastDeliveredID, federationusagecursor.FieldAttempts:
			values[i] = new(sql.NullInt64)
		case federationusagecursor.FieldScope, federationusagecursor.FieldLastError:
			values[i] = new(sql.NullString)
		case federationusagecursor.FieldCreatedAt, federationusagecursor.FieldUpdatedAt, federationusagecursor.FieldNextRetryAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FederationUsageCursor fields.
func (_m *FederationUsageCursor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case federationusagecursor.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case federationusagecursor.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case federationusagecursor.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case federationusagecursor.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = value.String
			}
		case federationusagecursor.FieldLastDeliveredID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_delivered_id", values[i])
			} else if value.Valid {
				_m.LastDeliveredID = value.Int64
			}
		case federationusagecursor.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				_m.Attempts = int(value.Int64)
			}
		case federationusagecursor.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case federationusagecursor.FieldNextRetryAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_retry_at", values[i])
			} else if value.Valid {
				_m.NextRetryAt = new(time.Time)
				*_m.NextRetryAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FederationUsageCursor.
// This includes values selected through modifiers, order, etc.
func (_m *FederationUsageCursor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this FederationUsageCursor.
// Note that you need to call FederationUsageCursor.Unwrap() before calling this method if this FederationUsageCursor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FederationUsageCursor) Update() *FederationUsageCursorUpdateOne {
	return NewFederationUsageCursorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FederationUsageCursor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FederationUsageCursor) Unwrap() *FederationUsageCursor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FederationUsageCursor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FederationUsageCursor) String() string {
	var builder strings.Builder
	builder.WriteString("FederationUsageCursor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(_m.Scope)
	builder.WriteString(", ")
	builder.WriteString("last_delivered_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastDeliveredID))
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.NextRetryAt; v != nil {
		builder.WriteString("next_retry_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// FederationUsageCursors is a parsable slice of FederationUsageCursor.
type FederationUsageCursors []*FederationUsageCursor
