// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/federationoutbox"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
)

// FederationOutboxUpdate is the builder for updating FederationOutbox entities.
type FederationOutboxUpdate struct {
	config
	hooks    []Hook
	mutation *FederationOutboxMutation
}

// Where appends a list predicates to the FederationOutboxUpdate builder.
func (_u *FederationOutboxUpdate) Where(ps ...predicate.FederationOutbox) *FederationOutboxUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FederationOutboxUpdate) SetUpdatedAt(v time.Time) *FederationOutboxUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAggregateType sets the "aggregate_type" field.
func (_u *FederationOutboxUpdate) SetAggregateType(v string) *FederationOutboxUpdate {
	_u.mutation.SetAggregateType(v)
	return _u
}

// SetNillableAggregateType sets the "aggregate_type" field if the given value is not nil.
func (_u *FederationOutboxUpdate) SetNillableAggregateType(v *string) *FederationOutboxUpdate {
	if v != nil {
		_u.SetAggregateType(*v)
	}
	return _u
}

// SetAggregateID sets the "aggregate_id" field.
func (_u *FederationOutboxUpdate) SetAggregateID(v string) *FederationOutboxUpdate {
	_u.mutation.SetAggregateID(v)
	return _u
}

// SetNillableAggregateID sets the "aggregate_id" field if the given value is not nil.
func (_u *FederationOutboxUpdate) SetNillableAggregateID(v *string) *FederationOutboxUpdate {
	if v != nil {
		_u.SetAggregateID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *FederationOutboxUpdate) SetEventType(v string) *FederationOutboxUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *FederationOutboxUpdate) SetNillableEventType(v *string) *FederationOutboxUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *FederationOutboxUpdate) SetPayload(v string) *FederationOutboxUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *FederationOutboxUpdate) SetNillablePayload(v *string) *FederationOutboxUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *FederationOutboxUpdate) SetStatus(v string) *FederationOutboxUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FederationOutboxUpdate) SetNillableStatus(v *string) *FederationOutboxUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *FederationOutboxUpdate) SetAttempts(v int) *FederationOutboxUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *FederationOutboxUpdate) SetNillableAttempts(v *int) *FederationOutboxUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *FederationOutboxUpdate) AddAttempts(v int) *FederationOutboxUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *FederationOutboxUpdate) SetLastError(v string) *FederationOutboxUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *FederationOutboxUpdate) SetNillableLastError(v *string) *FederationOutboxUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *FederationOutboxUpdate) ClearLastError() *FederationOutboxUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_u *FederationOutboxUpdate) SetNextRetryAt(v time.Time) *FederationOutboxUpdate {
	_u.mutation.SetNextRetryAt(v)
	return _u
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_u *FederationOutboxUpdate) SetNillableNextRetryAt(v *time.Time) *FederationOutboxUpdate {
	if v != nil {
		_u.SetNextRetryAt(*v)
	}
	return _u
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (_u *FederationOutboxUpdate) ClearNextRetryAt() *FederationOutboxUpdate {
	_u.mutation.ClearNextRetryAt()
	return _u
}

// Mutation returns the FederationOutboxMutation object of the builder.
func (_u *FederationOutboxUpdate) Mutation() *FederationOutboxMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FederationOutboxUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FederationOutboxUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FederationOutboxUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FederationOutboxUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FederationOutboxUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := federationoutbox.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FederationOutboxUpdate) check() error {
	if v, ok := _u.mutation.AggregateType(); ok {
		if err := federationoutbox.AggregateTypeValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_type", err: fmt.Errorf(`ent: validator failed for field "FederationOutbox.aggregate_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AggregateID(); ok {
		if err := federationoutbox.AggregateIDValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_id", err: fmt.Errorf(`ent: validator failed for field "FederationOutbox.aggregate_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := federationoutbox.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "FederationOutbox.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := federationoutbox.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FederationOutbox.status": %w`, err)}
		}
	}
	return nil
}

func (_u *FederationOutboxUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(federationoutbox.Table, federationoutbox.Columns, sqlgraph.NewFieldSpec(federationoutbox.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(federationoutbox.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AggregateType(); ok {
		_spec.SetField(federationoutbox.FieldAggregateType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AggregateID(); ok {
		_spec.SetField(federationoutbox.FieldAggregateID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(federationoutbox.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(federationoutbox.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(federationoutbox.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(federationoutbox.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(federationoutbox.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(federationoutbox.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(federationoutbox.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.NextRetryAt(); ok {
		_spec.SetField(federationoutbox.FieldNextRetryAt, field.TypeTime, value)
	}
	if _u.mutation.NextRetryAtCleared() {
		_spec.ClearField(federationoutbox.FieldNextRetryAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{federationoutbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FederationOutboxUpdateOne is the builder for updating a single FederationOutbox entity.
type FederationOutboxUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FederationOutboxMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FederationOutboxUpdateOne) SetUpdatedAt(v time.Time) *FederationOutboxUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAggregateType sets the "aggregate_type" field.
func (_u *FederationOutboxUpdateOne) SetAggregateType(v string) *FederationOutboxUpdateOne {
	_u.mutation.SetAggregateType(v)
	return _u
}

// SetNillableAggregateType sets the "aggregate_type" field if the given value is not nil.
func (_u *FederationOutboxUpdateOne) SetNillableAggregateType(v *string) *FederationOutboxUpdateOne {
	if v != nil {
		_u.SetAggregateType(*v)
	}
	return _u
}

// SetAggregateID sets the "aggregate_id" field.
func (_u *FederationOutboxUpdateOne) SetAggregateID(v string) *FederationOutboxUpdateOne {
	_u.mutation.SetAggregateID(v)
	return _u
}

// SetNillableAggregateID sets the "aggregate_id" field if the given value is not nil.
func (_u *FederationOutboxUpdateOne) SetNillableAggregateID(v *string) *FederationOutboxUpdateOne {
	if v != nil {
		_u.SetAggregateID(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *FederationOutboxUpdateOne) SetEventType(v string) *FederationOutboxUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *FederationOutboxUpdateOne) SetNillableEventType(v *string) *FederationOutboxUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *FederationOutboxUpdateOne) SetPayload(v string) *FederationOutboxUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *FederationOutboxUpdateOne) SetNillablePayload(v *string) *FederationOutboxUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *FederationOutboxUpdateOne) SetStatus(v string) *FederationOutboxUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FederationOutboxUpdateOne) SetNillableStatus(v *string) *FederationOutboxUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *FederationOutboxUpdateOne) SetAttempts(v int) *FederationOutboxUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *FederationOutboxUpdateOne) SetNillableAttempts(v *int) *FederationOutboxUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *FederationOutboxUpdateOne) AddAttempts(v int) *FederationOutboxUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *FederationOutboxUpdateOne) SetLastError(v string) *FederationOutboxUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *FederationOutboxUpdateOne) SetNillableLastError(v *string) *FederationOutboxUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *FederationOutboxUpdateOne) ClearLastError() *FederationOutboxUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_u *FederationOutboxUpdateOne) SetNextRetryAt(v time.Time) *FederationOutboxUpdateOne {
	_u.mutation.SetNextRetryAt(v)
	return _u
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_u *FederationOutboxUpdateOne) SetNillableNextRetryAt(v *time.Time) *FederationOutboxUpdateOne {
	if v != nil {
		_u.SetNextRetryAt(*v)
	}
	return _u
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (_u *FederationOutboxUpdateOne) ClearNextRetryAt() *FederationOutboxUpdateOne {
	_u.mutation.ClearNextRetryAt()
	return _u
}

// Mutation returns the FederationOutboxMutation object of the builder.
func (_u *FederationOutboxUpdateOne) Mutation() *FederationOutboxMutation {
	return _u.mutation
}

// Where appends a list predicates to the FederationOutboxUpdate builder.
func (_u *FederationOutboxUpdateOne) Where(ps ...predicate.FederationOutbox) *FederationOutboxUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FederationOutboxUpdateOne) Select(field string, fields ...string) *FederationOutboxUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FederationOutbox entity.
func (_u *FederationOutboxUpdateOne) Save(ctx context.Context) (*FederationOutbox, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FederationOutboxUpdateOne) SaveX(ctx context.Context) *FederationOutbox {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FederationOutboxUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FederationOutboxUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FederationOutboxUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := federationoutbox.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FederationOutboxUpdateOne) check() error {
	if v, ok := _u.mutation.AggregateType(); ok {
		if err := federationoutbox.AggregateTypeValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_type", err: fmt.Errorf(`ent: validator failed for field "FederationOutbox.aggregate_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AggregateID(); ok {
		if err := federationoutbox.AggregateIDValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_id", err: fmt.Errorf(`ent: validator failed for field "FederationOutbox.aggregate_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EventType(); ok {
		if err := federationoutbox.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "FederationOutbox.event_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := federationoutbox.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FederationOutbox.status": %w`, err)}
		}
	}
	return nil
}

func (_u *FederationOutboxUpdateOne) sqlSave(ctx context.Context) (_node *FederationOutbox, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(federationoutbox.Table, federationoutbox.Columns, sqlgraph.NewFieldSpec(federationoutbox.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FederationOutbox.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, federationoutbox.FieldID)
		for _, f := range fields {
			if !federationoutbox.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != federationoutbox.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(federationoutbox.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.AggregateType(); ok {
		_spec.SetField(federationoutbox.FieldAggregateType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AggregateID(); ok {
		_spec.SetField(federationoutbox.FieldAggregateID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(federationoutbox.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(federationoutbox.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(federationoutbox.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(federationoutbox.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(federationoutbox.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(federationoutbox.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(federationoutbox.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.NextRetryAt(); ok {
		_spec.SetField(federationoutbox.FieldNextRetryAt, field.TypeTime, value)
	}
	if _u.mutation.NextRetryAtCleared() {
		_spec.ClearField(federationoutbox.FieldNextRetryAt, field.TypeTime)
	}
	_node = &FederationOutbox{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{federationoutbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
