// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/federationoutbox"
)

// FederationOutboxCreate is the builder for creating a FederationOutbox entity.
type FederationOutboxCreate struct {
	config
	mutation *FederationOutboxMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *FederationOutboxCreate) SetCreatedAt(v time.Time) *FederationOutboxCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FederationOutboxCreate) SetNillableCreatedAt(v *time.Time) *FederationOutboxCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FederationOutboxCreate) SetUpdatedAt(v time.Time) *FederationOutboxCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FederationOutboxCreate) SetNillableUpdatedAt(v *time.Time) *FederationOutboxCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAggregateType sets the "aggregate_type" field.
func (_c *FederationOutboxCreate) SetAggregateType(v string) *FederationOutboxCreate {
	_c.mutation.SetAggregateType(v)
	return _c
}

// SetAggregateID sets the "aggregate_id" field.
func (_c *FederationOutboxCreate) SetAggregateID(v string) *FederationOutboxCreate {
	_c.mutation.SetAggregateID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *FederationOutboxCreate) SetEventType(v string) *FederationOutboxCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *FederationOutboxCreate) SetPayload(v string) *FederationOutboxCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *FederationOutboxCreate) SetStatus(v string) *FederationOutboxCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *FederationOutboxCreate) SetNillableStatus(v *string) *FederationOutboxCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *FederationOutboxCreate) SetAttempts(v int) *FederationOutboxCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *FederationOutboxCreate) SetNillableAttempts(v *int) *FederationOutboxCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *FederationOutboxCreate) SetLastError(v string) *FederationOutboxCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *FederationOutboxCreate) SetNillableLastError(v *string) *FederationOutboxCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_c *FederationOutboxCreate) SetNextRetryAt(v time.Time) *FederationOutboxCreate {
	_c.mutation.SetNextRetryAt(v)
	return _c
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_c *FederationOutboxCreate) SetNillableNextRetryAt(v *time.Time) *FederationOutboxCreate {
	if v != nil {
		_c.SetNextRetryAt(*v)
	}
	return _c
}

// Mutation returns the FederationOutboxMutation object of the builder.
func (_c *FederationOutboxCreate) Mutation() *FederationOutboxMutation {
	return _c.mutation
}

// Save creates the FederationOutbox in the database.
func (_c *FederationOutboxCreate) Save(ctx context.Context) (*FederationOutbox, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FederationOutboxCreate) SaveX(ctx context.Context) *FederationOutbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FederationOutboxCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FederationOutboxCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FederationOutboxCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := federationoutbox.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := federationoutbox.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := federationoutbox.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := federationoutbox.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FederationOutboxCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FederationOutbox.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FederationOutbox.updated_at"`)}
	}
	if _, ok := _c.mutation.AggregateType(); !ok {
		return &ValidationError{Name: "aggregate_type", err: errors.New(`ent: missing required field "FederationOutbox.aggregate_type"`)}
	}
	if v, ok := _c.mutation.AggregateType(); ok {
		if err := federationoutbox.AggregateTypeValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_type", err: fmt.Errorf(`ent: validator failed for field "FederationOutbox.aggregate_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AggregateID(); !ok {
		return &ValidationError{Name: "aggregate_id", err: errors.New(`ent: missing required field "FederationOutbox.aggregate_id"`)}
	}
	if v, ok := _c.mutation.AggregateID(); ok {
		if err := federationoutbox.AggregateIDValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_id", err: fmt.Errorf(`ent: validator failed for field "FederationOutbox.aggregate_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "FederationOutbox.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := federationoutbox.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "FederationOutbox.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "FederationOutbox.payload"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "FederationOutbox.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := federationoutbox.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FederationOutbox.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "FederationOutbox.attempts"`)}
	}
	return nil
}

func (_c *FederationOutboxCreate) sqlSave(ctx context.Context) (*FederationOutbox, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FederationOutboxCreate) createSpec() (*FederationOutbox, *sqlgraph.CreateSpec) {
	var (
		_node = &FederationOutbox{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(federationoutbox.Table, sqlgraph.NewFieldSpec(federationoutbox.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(federationoutbox.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(federationoutbox.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AggregateType(); ok {
		_spec.SetField(federationoutbox.FieldAggregateType, field.TypeString, value)
		_node.AggregateType = value
	}
	if value, ok := _c.mutation.AggregateID(); ok {
		_spec.SetField(federationoutbox.FieldAggregateID, field.TypeString, value)
		_node.AggregateID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(federationoutbox.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(federationoutbox.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(federationoutbox.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(federationoutbox.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(federationoutbox.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.NextRetryAt(); ok {
		_spec.SetField(federationoutbox.FieldNextRetryAt, field.TypeTime, value)
		_node.NextRetryAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FederationOutbox.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FederationOutboxUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FederationOutboxCreate) OnConflict(opts ...sql.ConflictOption) *FederationOutboxUpsertOne {
	_c.conflict = opts
	return &FederationOutboxUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FederationOutbox.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FederationOutboxCreate) OnConflictColumns(columns ...string) *FederationOutboxUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FederationOutboxUpsertOne{
		create: _c,
	}
}

type (
	// FederationOutboxUpsertOne is the builder for "upsert"-ing
	//  one FederationOutbox node.
	FederationOutboxUpsertOne struct {
		create *FederationOutboxCreate
	}

	// FederationOutboxUpsert is the "OnConflict" setter.
	FederationOutboxUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *FederationOutboxUpsert) SetUpdatedAt(v time.Time) *FederationOutboxUpsert {
	u.Set(federationoutbox.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FederationOutboxUpsert) UpdateUpdatedAt() *FederationOutboxUpsert {
	u.SetExcluded(federationoutbox.FieldUpdatedAt)
	return u
}

// SetAggregateType sets the "aggregate_type" field.
func (u *FederationOutboxUpsert) SetAggregateType(v string) *FederationOutboxUpsert {
	u.Set(federationoutbox.FieldAggregateType, v)
	return u
}

// UpdateAggregateType sets the "aggregate_type" field to the value that was provided on create.
func (u *FederationOutboxUpsert) UpdateAggregateType() *FederationOutboxUpsert {
	u.SetExcluded(federationoutbox.FieldAggregateType)
	return u
}

// SetAggregateID sets the "aggregate_id" field.
func (u *FederationOutboxUpsert) SetAggregateID(v string) *FederationOutboxUpsert {
	u.Set(federationoutbox.FieldAggregateID, v)
	return u
}

// UpdateAggregateID sets the "aggregate_id" field to the value that was provided on create.
func (u *FederationOutboxUpsert) UpdateAggregateID() *FederationOutboxUpsert {
	u.SetExcluded(federationoutbox.FieldAggregateID)
	return u
}

// SetEventType sets the "event_type" field.
func (u *FederationOutboxUpsert) SetEventType(v string) *FederationOutboxUpsert {
	u.Set(federationoutbox.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *FederationOutboxUpsert) UpdateEventType() *FederationOutboxUpsert {
	u.SetExcluded(federationoutbox.FieldEventType)
	return u
}

// SetPayload sets the "payload" field.
func (u *FederationOutboxUpsert) SetPayload(v string) *FederationOutboxUpsert {
	u.Set(federationoutbox.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *FederationOutboxUpsert) UpdatePayload() *FederationOutboxUpsert {
	u.SetExcluded(federationoutbox.FieldPayload)
	return u
}

// SetStatus sets the "status" field.
func (u *FederationOutboxUpsert) SetStatus(v string) *FederationOutboxUpsert {
	u.Set(federationoutbox.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FederationOutboxUpsert) UpdateStatus() *FederationOutboxUpsert {
	u.SetExcluded(federationoutbox.FieldStatus)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *FederationOutboxUpsert) SetAttempts(v int) *FederationOutboxUpsert {
	u.Set(federationoutbox.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *FederationOutboxUpsert) UpdateAttempts() *FederationOutboxUpsert {
	u.SetExcluded(federationoutbox.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *FederationOutboxUpsert) AddAttempts(v int) *FederationOutboxUpsert {
	u.Add(federationoutbox.FieldAttempts, v)
	return u
}

// SetLastError sets the "last_error" field.
func (u *FederationOutboxUpsert) SetLastError(v string) *FederationOutboxUpsert {
	u.Set(federationoutbox.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *FederationOutboxUpsert) UpdateLastError() *FederationOutboxUpsert {
	u.SetExcluded(federationoutbox.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *FederationOutboxUpsert) ClearLastError() *FederationOutboxUpsert {
	u.SetNull(federationoutbox.FieldLastError)
	return u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (u *FederationOutboxUpsert) SetNextRetryAt(v time.Time) *FederationOutboxUpsert {
	u.Set(federationoutbox.FieldNextRetryAt, v)
	return u
}

// UpdateNextRetryAt sets the "next_retry_at" field to the value that was provided on create.
func (u *FederationOutboxUpsert) UpdateNextRetryAt() *FederationOutboxUpsert {
	u.SetExcluded(federationoutbox.FieldNextRetryAt)
	return u
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (u *FederationOutboxUpsert) ClearNextRetryAt() *FederationOutboxUpsert {
	u.SetNull(federationoutbox.FieldNextRetryAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FederationOutbox.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FederationOutboxUpsertOne) UpdateNewValues() *FederationOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(federationoutbox.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FederationOutbox.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FederationOutboxUpsertOne) Ignore() *FederationOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FederationOutboxUpsertOne) DoNothing() *FederationOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FederationOutboxCreate.OnConflict
// documentation for more info.
func (u *FederationOutboxUpsertOne) Update(set func(*FederationOutboxUpsert)) *FederationOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FederationOutboxUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FederationOutboxUpsertOne) SetUpdatedAt(v time.Time) *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FederationOutboxUpsertOne) UpdateUpdatedAt() *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAggregateType sets the "aggregate_type" field.
func (u *FederationOutboxUpsertOne) SetAggregateType(v string) *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetAggregateType(v)
	})
}

// UpdateAggregateType sets the "aggregate_type" field to the value that was provided on create.
func (u *FederationOutboxUpsertOne) UpdateAggregateType() *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateAggregateType()
	})
}

// SetAggregateID sets the "aggregate_id" field.
func (u *FederationOutboxUpsertOne) SetAggregateID(v string) *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetAggregateID(v)
	})
}

// UpdateAggregateID sets the "aggregate_id" field to the value that was provided on create.
func (u *FederationOutboxUpsertOne) UpdateAggregateID() *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateAggregateID()
	})
}

// SetEventType sets the "event_type" field.
func (u *FederationOutboxUpsertOne) SetEventType(v string) *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *FederationOutboxUpsertOne) UpdateEventType() *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateEventType()
	})
}

// SetPayload sets the "payload" field.
func (u *FederationOutboxUpsertOne) SetPayload(v string) *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *FederationOutboxUpsertOne) UpdatePayload() *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdatePayload()
	})
}

// SetStatus sets the "status" field.
func (u *FederationOutboxUpsertOne) SetStatus(v string) *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FederationOutboxUpsertOne) UpdateStatus() *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateStatus()
	})
}

// SetAttempts sets the "attempts" field.
func (u *FederationOutboxUpsertOne) SetAttempts(v int) *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *FederationOutboxUpsertOne) AddAttempts(v int) *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *FederationOutboxUpsertOne) UpdateAttempts() *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *FederationOutboxUpsertOne) SetLastError(v string) *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *FederationOutboxUpsertOne) UpdateLastError() *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *FederationOutboxUpsertOne) ClearLastError() *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.ClearLastError()
	})
}

// SetNextRetryAt sets the "next_retry_at" field.
func (u *FederationOutboxUpsertOne) SetNextRetryAt(v time.Time) *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetNextRetryAt(v)
	})
}

// UpdateNextRetryAt sets the "next_retry_at" field to the value that was provided on create.
func (u *FederationOutboxUpsertOne) UpdateNextRetryAt() *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateNextRetryAt()
	})
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (u *FederationOutboxUpsertOne) ClearNextRetryAt() *FederationOutboxUpsertOne {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.ClearNextRetryAt()
	})
}

// Exec executes the query.
func (u *FederationOutboxUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FederationOutboxCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FederationOutboxUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FederationOutboxUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FederationOutboxUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FederationOutboxCreateBulk is the builder for creating many FederationOutbox entities in bulk.
type FederationOutboxCreateBulk struct {
	config
	err      error
	builders []*FederationOutboxCreate
	conflict []sql.ConflictOption
}

// Save creates the FederationOutbox entities in the database.
func (_c *FederationOutboxCreateBulk) Save(ctx context.Context) ([]*FederationOutbox, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FederationOutbox, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FederationOutboxMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FederationOutboxCreateBulk) SaveX(ctx context.Context) []*FederationOutbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FederationOutboxCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FederationOutboxCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FederationOutbox.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FederationOutboxUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FederationOutboxCreateBulk) OnConflict(opts ...sql.ConflictOption) *FederationOutboxUpsertBulk {
	_c.conflict = opts
	return &FederationOutboxUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FederationOutbox.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FederationOutboxCreateBulk) OnConflictColumns(columns ...string) *FederationOutboxUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FederationOutboxUpsertBulk{
		create: _c,
	}
}

// FederationOutboxUpsertBulk is the builder for "upsert"-ing
// a bulk of FederationOutbox nodes.
type FederationOutboxUpsertBulk struct {
	create *FederationOutboxCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FederationOutbox.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FederationOutboxUpsertBulk) UpdateNewValues() *FederationOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(federationoutbox.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FederationOutbox.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FederationOutboxUpsertBulk) Ignore() *FederationOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FederationOutboxUpsertBulk) DoNothing() *FederationOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FederationOutboxCreateBulk.OnConflict
// documentation for more info.
func (u *FederationOutboxUpsertBulk) Update(set func(*FederationOutboxUpsert)) *FederationOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FederationOutboxUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FederationOutboxUpsertBulk) SetUpdatedAt(v time.Time) *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FederationOutboxUpsertBulk) UpdateUpdatedAt() *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAggregateType sets the "aggregate_type" field.
func (u *FederationOutboxUpsertBulk) SetAggregateType(v string) *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetAggregateType(v)
	})
}

// UpdateAggregateType sets the "aggregate_type" field to the value that was provided on create.
func (u *FederationOutboxUpsertBulk) UpdateAggregateType() *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateAggregateType()
	})
}

// SetAggregateID sets the "aggregate_id" field.
func (u *FederationOutboxUpsertBulk) SetAggregateID(v string) *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetAggregateID(v)
	})
}

// UpdateAggregateID sets the "aggregate_id" field to the value that was provided on create.
func (u *FederationOutboxUpsertBulk) UpdateAggregateID() *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateAggregateID()
	})
}

// SetEventType sets the "event_type" field.
func (u *FederationOutboxUpsertBulk) SetEventType(v string) *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *FederationOutboxUpsertBulk) UpdateEventType() *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateEventType()
	})
}

// SetPayload sets the "payload" field.
func (u *FederationOutboxUpsertBulk) SetPayload(v string) *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *FederationOutboxUpsertBulk) UpdatePayload() *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdatePayload()
	})
}

// SetStatus sets the "status" field.
func (u *FederationOutboxUpsertBulk) SetStatus(v string) *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *FederationOutboxUpsertBulk) UpdateStatus() *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateStatus()
	})
}

// SetAttempts sets the "attempts" field.
func (u *FederationOutboxUpsertBulk) SetAttempts(v int) *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *FederationOutboxUpsertBulk) AddAttempts(v int) *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *FederationOutboxUpsertBulk) UpdateAttempts() *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *FederationOutboxUpsertBulk) SetLastError(v string) *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *FederationOutboxUpsertBulk) UpdateLastError() *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *FederationOutboxUpsertBulk) ClearLastError() *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.ClearLastError()
	})
}

// SetNextRetryAt sets the "next_retry_at" field.
func (u *FederationOutboxUpsertBulk) SetNextRetryAt(v time.Time) *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.SetNextRetryAt(v)
	})
}

// UpdateNextRetryAt sets the "next_retry_at" field to the value that was provided on create.
func (u *FederationOutboxUpsertBulk) UpdateNextRetryAt() *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.UpdateNextRetryAt()
	})
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (u *FederationOutboxUpsertBulk) ClearNextRetryAt() *FederationOutboxUpsertBulk {
	return u.Update(func(s *FederationOutboxUpsert) {
		s.ClearNextRetryAt()
	})
}

// Exec executes the query.
func (u *FederationOutboxUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FederationOutboxCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FederationOutboxCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FederationOutboxUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
