// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/federationusagecursor"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
)

// FederationUsageCursorUpdate is the builder for updating FederationUsageCursor entities.
type FederationUsageCursorUpdate struct {
	config
	hooks    []Hook
	mutation *FederationUsageCursorMutation
}

// Where appends a list predicates to the FederationUsageCursorUpdate builder.
func (_u *FederationUsageCursorUpdate) Where(ps ...predicate.FederationUsageCursor) *FederationUsageCursorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FederationUsageCursorUpdate) SetUpdatedAt(v time.Time) *FederationUsageCursorUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetScope sets the "scope" field.
func (_u *FederationUsageCursorUpdate) SetScope(v string) *FederationUsageCursorUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *FederationUsageCursorUpdate) SetNillableScope(v *string) *FederationUsageCursorUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetLastDeliveredID sets the "last_delivered_id" field.
func (_u *FederationUsageCursorUpdate) SetLastDeliveredID(v int64) *FederationUsageCursorUpdate {
	_u.mutation.ResetLastDeliveredID()
	_u.mutation.SetLastDeliveredID(v)
	return _u
}

// SetNillableLastDeliveredID sets the "last_delivered_id" field if the given value is not nil.
func (_u *FederationUsageCursorUpdate) SetNillableLastDeliveredID(v *int64) *FederationUsageCursorUpdate {
	if v != nil {
		_u.SetLastDeliveredID(*v)
	}
	return _u
}

// AddLastDeliveredID adds value to the "last_delivered_id" field.
func (_u *FederationUsageCursorUpdate) AddLastDeliveredID(v int64) *FederationUsageCursorUpdate {
	_u.mutation.AddLastDeliveredID(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *FederationUsageCursorUpdate) SetAttempts(v int) *FederationUsageCursorUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *FederationUsageCursorUpdate) SetNillableAttempts(v *int) *FederationUsageCursorUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *FederationUsageCursorUpdate) AddAttempts(v int) *FederationUsageCursorUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *FederationUsageCursorUpdate) SetLastError(v string) *FederationUsageCursorUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *FederationUsageCursorUpdate) SetNillableLastError(v *string) *FederationUsageCursorUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *FederationUsageCursorUpdate) ClearLastError() *FederationUsageCursorUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_u *FederationUsageCursorUpdate) SetNextRetryAt(v time.Time) *FederationUsageCursorUpdate {
	_u.mutation.SetNextRetryAt(v)
	return _u
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_u *FederationUsageCursorUpdate) SetNillableNextRetryAt(v *time.Time) *FederationUsageCursorUpdate {
	if v != nil {
		_u.SetNextRetryAt(*v)
	}
	return _u
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (_u *FederationUsageCursorUpdate) ClearNextRetryAt() *FederationUsageCursorUpdate {
	_u.mutation.ClearNextRetryAt()
	return _u
}

// Mutation returns the FederationUsageCursorMutation object of the builder.
func (_u *FederationUsageCursorUpdate) Mutation() *FederationUsageCursorMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FederationUsageCursorUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FederationUsageCursorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FederationUsageCursorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FederationUsageCursorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FederationUsageCursorUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := federationusagecursor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FederationUsageCursorUpdate) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := federationusagecursor.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "FederationUsageCursor.scope": %w`, err)}
		}
	}
	return nil
}

func (_u *FederationUsageCursorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(federationusagecursor.Table, federationusagecursor.Columns, sqlgraph.NewFieldSpec(federationusagecursor.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(federationusagecursor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(federationusagecursor.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastDeliveredID(); ok {
		_spec.SetField(federationusagecursor.FieldLastDeliveredID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastDeliveredID(); ok {
		_spec.AddField(federationusagecursor.FieldLastDeliveredID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(federationusagecursor.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(federationusagecursor.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(federationusagecursor.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(federationusagecursor.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.NextRetryAt(); ok {
		_spec.SetField(federationusagecursor.FieldNextRetryAt, field.TypeTime, value)
	}
	if _u.mutation.NextRetryAtCleared() {
		_spec.ClearField(federationusagecursor.FieldNextRetryAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{federationusagecursor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FederationUsageCursorUpdateOne is the builder for updating a single FederationUsageCursor entity.
type FederationUsageCursorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FederationUsageCursorMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FederationUsageCursorUpdateOne) SetUpdatedAt(v time.Time) *FederationUsageCursorUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetScope sets the "scope" field.
func (_u *FederationUsageCursorUpdateOne) SetScope(v string) *FederationUsageCursorUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *FederationUsageCursorUpdateOne) SetNillableScope(v *string) *FederationUsageCursorUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetLastDeliveredID sets the "last_delivered_id" field.
func (_u *FederationUsageCursorUpdateOne) SetLastDeliveredID(v int64) *FederationUsageCursorUpdateOne {
	_u.mutation.ResetLastDeliveredID()
	_u.mutation.SetLastDeliveredID(v)
	return _u
}

// SetNillableLastDeliveredID sets the "last_delivered_id" field if the given value is not nil.
func (_u *FederationUsageCursorUpdateOne) SetNillableLastDeliveredID(v *int64) *FederationUsageCursorUpdateOne {
	if v != nil {
		_u.SetLastDeliveredID(*v)
	}
	return _u
}

// AddLastDeliveredID adds value to the "last_delivered_id" field.
func (_u *FederationUsageCursorUpdateOne) AddLastDeliveredID(v int64) *FederationUsageCursorUpdateOne {
	_u.mutation.AddLastDeliveredID(v)
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *FederationUsageCursorUpdateOne) SetAttempts(v int) *FederationUsageCursorUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *FederationUsageCursorUpdateOne) SetNillableAttempts(v *int) *FederationUsageCursorUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *FederationUsageCursorUpdateOne) AddAttempts(v int) *FederationUsageCursorUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *FederationUsageCursorUpdateOne) SetLastError(v string) *FederationUsageCursorUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *FederationUsageCursorUpdateOne) SetNillableLastError(v *string) *FederationUsageCursorUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *FederationUsageCursorUpdateOne) ClearLastError() *FederationUsageCursorUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_u *FederationUsageCursorUpdateOne) SetNextRetryAt(v time.Time) *FederationUsageCursorUpdateOne {
	_u.mutation.SetNextRetryAt(v)
	return _u
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_u *FederationUsageCursorUpdateOne) SetNillableNextRetryAt(v *time.Time) *FederationUsageCursorUpdateOne {
	if v != nil {
		_u.SetNextRetryAt(*v)
	}
	return _u
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (_u *FederationUsageCursorUpdateOne) ClearNextRetryAt() *FederationUsageCursorUpdateOne {
	_u.mutation.ClearNextRetryAt()
	return _u
}

// Mutation returns the FederationUsageCursorMutation object of the builder.
func (_u *FederationUsageCursorUpdateOne) Mutation() *FederationUsageCursorMutation {
	return _u.mutation
}

// Where appends a list predicates to the FederationUsageCursorUpdate builder.
func (_u *FederationUsageCursorUpdateOne) Where(ps ...predicate.FederationUsageCursor) *FederationUsageCursorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FederationUsageCursorUpdateOne) Select(field string, fields ...string) *FederationUsageCursorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FederationUsageCursor entity.
func (_u *FederationUsageCursorUpdateOne) Save(ctx context.Context) (*FederationUsageCursor, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FederationUsageCursorUpdateOne) SaveX(ctx context.Context) *FederationUsageCursor {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FederationUsageCursorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FederationUsageCursorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FederationUsageCursorUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := federationusagecursor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FederationUsageCursorUpdateOne) check() error {
	if v, ok := _u.mutation.Scope(); ok {
		if err := federationusagecursor.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "FederationUsageCursor.scope": %w`, err)}
		}
	}
	return nil
}

func (_u *FederationUsageCursorUpdateOne) sqlSave(ctx context.Context) (_node *FederationUsageCursor, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(federationusagecursor.Table, federationusagecursor.Columns, sqlgraph.NewFieldSpec(federationusagecursor.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FederationUsageCursor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, federationusagecursor.FieldID)
		for _, f := range fields {
			if !federationusagecursor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != federationusagecursor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(federationusagecursor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(federationusagecursor.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastDeliveredID(); ok {
		_spec.SetField(federationusagecursor.FieldLastDeliveredID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastDeliveredID(); ok {
		_spec.AddField(federationusagecursor.FieldLastDeliveredID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(federationusagecursor.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(federationusagecursor.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(federationusagecursor.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(federationusagecursor.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.NextRetryAt(); ok {
		_spec.SetField(federationusagecursor.FieldNextRetryAt, field.TypeTime, value)
	}
	if _u.mutation.NextRetryAtCleared() {
		_spec.ClearField(federationusagecursor.FieldNextRetryAt, field.TypeTime)
	}
	_node = &FederationUsageCursor{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{federationusagecursor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
