// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/LuckyKuang/sub2api-plus/ent/federationusagecursor"
)

// FederationUsageCursorCreate is the builder for creating a FederationUsageCursor entity.
type FederationUsageCursorCreate struct {
	config
	mutation *FederationUsageCursorMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *FederationUsageCursorCreate) SetCreatedAt(v time.Time) *FederationUsageCursorCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FederationUsageCursorCreate) SetNillableCreatedAt(v *time.Time) *FederationUsageCursorCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FederationUsageCursorCreate) SetUpdatedAt(v time.Time) *FederationUsageCursorCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FederationUsageCursorCreate) SetNillableUpdatedAt(v *time.Time) *FederationUsageCursorCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetScope sets the "scope" field.
func (_c *FederationUsageCursorCreate) SetScope(v string) *FederationUsageCursorCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetLastDeliveredID sets the "last_delivered_id" field.
func (_c *FederationUsageCursorCreate) SetLastDeliveredID(v int64) *FederationUsageCursorCreate {
	_c.mutation.SetLastDeliveredID(v)
	return _c
}

// SetNillableLastDeliveredID sets the "last_delivered_id" field if the given value is not nil.
func (_c *FederationUsageCursorCreate) SetNillableLastDeliveredID(v *int64) *FederationUsageCursorCreate {
	if v != nil {
		_c.SetLastDeliveredID(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *FederationUsageCursorCreate) SetAttempts(v int) *FederationUsageCursorCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *FederationUsageCursorCreate) SetNillableAttempts(v *int) *FederationUsageCursorCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *FederationUsageCursorCreate) SetLastError(v string) *FederationUsageCursorCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *FederationUsageCursorCreate) SetNillableLastError(v *string) *FederationUsageCursorCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_c *FederationUsageCursorCreate) SetNextRetryAt(v time.Time) *FederationUsageCursorCreate {
	_c.mutation.SetNextRetryAt(v)
	return _c
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_c *FederationUsageCursorCreate) SetNillableNextRetryAt(v *time.Time) *FederationUsageCursorCreate {
	if v != nil {
		_c.SetNextRetryAt(*v)
	}
	return _c
}

// Mutation returns the FederationUsageCursorMutation object of the builder.
func (_c *FederationUsageCursorCreate) Mutation() *FederationUsageCursorMutation {
	return _c.mutation
}

// Save creates the FederationUsageCursor in the database.
func (_c *FederationUsageCursorCreate) Save(ctx context.Context) (*FederationUsageCursor, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FederationUsageCursorCreate) SaveX(ctx context.Context) *FederationUsageCursor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FederationUsageCursorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FederationUsageCursorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FederationUsageCursorCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := federationusagecursor.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := federationusagecursor.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.LastDeliveredID(); !ok {
		v := federationusagecursor.DefaultLastDeliveredID
		_c.mutation.SetLastDeliveredID(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := federationusagecursor.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FederationUsageCursorCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FederationUsageCursor.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FederationUsageCursor.updated_at"`)}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "FederationUsageCursor.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := federationusagecursor.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "FederationUsageCursor.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastDeliveredID(); !ok {
		return &ValidationError{Name: "last_delivered_id", err: errors.New(`ent: missing required field "FederationUsageCursor.last_delivered_id"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "FederationUsageCursor.attempts"`)}
	}
	return nil
}

func (_c *FederationUsageCursorCreate) sqlSave(ctx context.Context) (*FederationUsageCursor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FederationUsageCursorCreate) createSpec() (*FederationUsageCursor, *sqlgraph.CreateSpec) {
	var (
		_node = &FederationUsageCursor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(federationusagecursor.Table, sqlgraph.NewFieldSpec(federationusagecursor.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(federationusagecursor.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(federationusagecursor.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(federationusagecursor.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.LastDeliveredID(); ok {
		_spec.SetField(federationusagecursor.FieldLastDeliveredID, field.TypeInt64, value)
		_node.LastDeliveredID = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(federationusagecursor.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(federationusagecursor.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.NextRetryAt(); ok {
		_spec.SetField(federationusagecursor.FieldNextRetryAt, field.TypeTime, value)
		_node.NextRetryAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FederationUsageCursor.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FederationUsageCursorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FederationUsageCursorCreate) OnConflict(opts ...sql.ConflictOption) *FederationUsageCursorUpsertOne {
	_c.conflict = opts
	return &FederationUsageCursorUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FederationUsageCursor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FederationUsageCursorCreate) OnConflictColumns(columns ...string) *FederationUsageCursorUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FederationUsageCursorUpsertOne{
		create: _c,
	}
}

type (
	// FederationUsageCursorUpsertOne is the builder for "upsert"-ing
	//  one FederationUsageCursor node.
	FederationUsageCursorUpsertOne struct {
		create *FederationUsageCursorCreate
	}

	// FederationUsageCursorUpsert is the "OnConflict" setter.
	FederationUsageCursorUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *FederationUsageCursorUpsert) SetUpdatedAt(v time.Time) *FederationUsageCursorUpsert {
	u.Set(federationusagecursor.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FederationUsageCursorUpsert) UpdateUpdatedAt() *FederationUsageCursorUpsert {
	u.SetExcluded(federationusagecursor.FieldUpdatedAt)
	return u
}

// SetScope sets the "scope" field.
func (u *FederationUsageCursorUpsert) SetScope(v string) *FederationUsageCursorUpsert {
	u.Set(federationusagecursor.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *FederationUsageCursorUpsert) UpdateScope() *FederationUsageCursorUpsert {
	u.SetExcluded(federationusagecursor.FieldScope)
	return u
}

// SetLastDeliveredID sets the "last_delivered_id" field.
func (u *FederationUsageCursorUpsert) SetLastDeliveredID(v int64) *FederationUsageCursorUpsert {
	u.Set(federationusagecursor.FieldLastDeliveredID, v)
	return u
}

// UpdateLastDeliveredID sets the "last_delivered_id" field to the value that was provided on create.
func (u *FederationUsageCursorUpsert) UpdateLastDeliveredID() *FederationUsageCursorUpsert {
	u.SetExcluded(federationusagecursor.FieldLastDeliveredID)
	return u
}

// AddLastDeliveredID adds v to the "last_delivered_id" field.
func (u *FederationUsageCursorUpsert) AddLastDeliveredID(v int64) *FederationUsageCursorUpsert {
	u.Add(federationusagecursor.FieldLastDeliveredID, v)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *FederationUsageCursorUpsert) SetAttempts(v int) *FederationUsageCursorUpsert {
	u.Set(federationusagecursor.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *FederationUsageCursorUpsert) UpdateAttempts() *FederationUsageCursorUpsert {
	u.SetExcluded(federationusagecursor.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *FederationUsageCursorUpsert) AddAttempts(v int) *FederationUsageCursorUpsert {
	u.Add(federationusagecursor.FieldAttempts, v)
	return u
}

// SetLastError sets the "last_error" field.
func (u *FederationUsageCursorUpsert) SetLastError(v string) *FederationUsageCursorUpsert {
	u.Set(federationusagecursor.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *FederationUsageCursorUpsert) UpdateLastError() *FederationUsageCursorUpsert {
	u.SetExcluded(federationusagecursor.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *FederationUsageCursorUpsert) ClearLastError() *FederationUsageCursorUpsert {
	u.SetNull(federationusagecursor.FieldLastError)
	return u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (u *FederationUsageCursorUpsert) SetNextRetryAt(v time.Time) *FederationUsageCursorUpsert {
	u.Set(federationusagecursor.FieldNextRetryAt, v)
	return u
}

// UpdateNextRetryAt sets the "next_retry_at" field to the value that was provided on create.
func (u *FederationUsageCursorUpsert) UpdateNextRetryAt() *FederationUsageCursorUpsert {
	u.SetExcluded(federationusagecursor.FieldNextRetryAt)
	return u
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (u *FederationUsageCursorUpsert) ClearNextRetryAt() *FederationUsageCursorUpsert {
	u.SetNull(federationusagecursor.FieldNextRetryAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.FederationUsageCursor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FederationUsageCursorUpsertOne) UpdateNewValues() *FederationUsageCursorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(federationusagecursor.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FederationUsageCursor.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *FederationUsageCursorUpsertOne) Ignore() *FederationUsageCursorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FederationUsageCursorUpsertOne) DoNothing() *FederationUsageCursorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FederationUsageCursorCreate.OnConflict
// documentation for more info.
func (u *FederationUsageCursorUpsertOne) Update(set func(*FederationUsageCursorUpsert)) *FederationUsageCursorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FederationUsageCursorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FederationUsageCursorUpsertOne) SetUpdatedAt(v time.Time) *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FederationUsageCursorUpsertOne) UpdateUpdatedAt() *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetScope sets the "scope" field.
func (u *FederationUsageCursorUpsertOne) SetScope(v string) *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *FederationUsageCursorUpsertOne) UpdateScope() *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.UpdateScope()
	})
}

// SetLastDeliveredID sets the "last_delivered_id" field.
func (u *FederationUsageCursorUpsertOne) SetLastDeliveredID(v int64) *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.SetLastDeliveredID(v)
	})
}

// AddLastDeliveredID adds v to the "last_delivered_id" field.
func (u *FederationUsageCursorUpsertOne) AddLastDeliveredID(v int64) *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.AddLastDeliveredID(v)
	})
}

// UpdateLastDeliveredID sets the "last_delivered_id" field to the value that was provided on create.
func (u *FederationUsageCursorUpsertOne) UpdateLastDeliveredID() *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.UpdateLastDeliveredID()
	})
}

// SetAttempts sets the "attempts" field.
func (u *FederationUsageCursorUpsertOne) SetAttempts(v int) *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *FederationUsageCursorUpsertOne) AddAttempts(v int) *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *FederationUsageCursorUpsertOne) UpdateAttempts() *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *FederationUsageCursorUpsertOne) SetLastError(v string) *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *FederationUsageCursorUpsertOne) UpdateLastError() *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *FederationUsageCursorUpsertOne) ClearLastError() *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.ClearLastError()
	})
}

// SetNextRetryAt sets the "next_retry_at" field.
func (u *FederationUsageCursorUpsertOne) SetNextRetryAt(v time.Time) *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.SetNextRetryAt(v)
	})
}

// UpdateNextRetryAt sets the "next_retry_at" field to the value that was provided on create.
func (u *FederationUsageCursorUpsertOne) UpdateNextRetryAt() *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.UpdateNextRetryAt()
	})
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (u *FederationUsageCursorUpsertOne) ClearNextRetryAt() *FederationUsageCursorUpsertOne {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.ClearNextRetryAt()
	})
}

// Exec executes the query.
func (u *FederationUsageCursorUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FederationUsageCursorCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FederationUsageCursorUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FederationUsageCursorUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FederationUsageCursorUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FederationUsageCursorCreateBulk is the builder for creating many FederationUsageCursor entities in bulk.
type FederationUsageCursorCreateBulk struct {
	config
	err      error
	builders []*FederationUsageCursorCreate
	conflict []sql.ConflictOption
}

// Save creates the FederationUsageCursor entities in the database.
func (_c *FederationUsageCursorCreateBulk) Save(ctx context.Context) ([]*FederationUsageCursor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FederationUsageCursor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FederationUsageCursorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FederationUsageCursorCreateBulk) SaveX(ctx context.Context) []*FederationUsageCursor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FederationUsageCursorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FederationUsageCursorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FederationUsageCursor.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.FederationUsageCursorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *FederationUsageCursorCreateBulk) OnConflict(opts ...sql.ConflictOption) *FederationUsageCursorUpsertBulk {
	_c.conflict = opts
	return &FederationUsageCursorUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.FederationUsageCursor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *FederationUsageCursorCreateBulk) OnConflictColumns(columns ...string) *FederationUsageCursorUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &FederationUsageCursorUpsertBulk{
		create: _c,
	}
}

// FederationUsageCursorUpsertBulk is the builder for "upsert"-ing
// a bulk of FederationUsageCursor nodes.
type FederationUsageCursorUpsertBulk struct {
	create *FederationUsageCursorCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.FederationUsageCursor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *FederationUsageCursorUpsertBulk) UpdateNewValues() *FederationUsageCursorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(federationusagecursor.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.FederationUsageCursor.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *FederationUsageCursorUpsertBulk) Ignore() *FederationUsageCursorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *FederationUsageCursorUpsertBulk) DoNothing() *FederationUsageCursorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the FederationUsageCursorCreateBulk.OnConflict
// documentation for more info.
func (u *FederationUsageCursorUpsertBulk) Update(set func(*FederationUsageCursorUpsert)) *FederationUsageCursorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FederationUsageCursorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *FederationUsageCursorUpsertBulk) SetUpdatedAt(v time.Time) *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *FederationUsageCursorUpsertBulk) UpdateUpdatedAt() *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetScope sets the "scope" field.
func (u *FederationUsageCursorUpsertBulk) SetScope(v string) *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *FederationUsageCursorUpsertBulk) UpdateScope() *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.UpdateScope()
	})
}

// SetLastDeliveredID sets the "last_delivered_id" field.
func (u *FederationUsageCursorUpsertBulk) SetLastDeliveredID(v int64) *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.SetLastDeliveredID(v)
	})
}

// AddLastDeliveredID adds v to the "last_delivered_id" field.
func (u *FederationUsageCursorUpsertBulk) AddLastDeliveredID(v int64) *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.AddLastDeliveredID(v)
	})
}

// UpdateLastDeliveredID sets the "last_delivered_id" field to the value that was provided on create.
func (u *FederationUsageCursorUpsertBulk) UpdateLastDeliveredID() *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.UpdateLastDeliveredID()
	})
}

// SetAttempts sets the "attempts" field.
func (u *FederationUsageCursorUpsertBulk) SetAttempts(v int) *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *FederationUsageCursorUpsertBulk) AddAttempts(v int) *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *FederationUsageCursorUpsertBulk) UpdateAttempts() *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *FederationUsageCursorUpsertBulk) SetLastError(v string) *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *FederationUsageCursorUpsertBulk) UpdateLastError() *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *FederationUsageCursorUpsertBulk) ClearLastError() *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.ClearLastError()
	})
}

// SetNextRetryAt sets the "next_retry_at" field.
func (u *FederationUsageCursorUpsertBulk) SetNextRetryAt(v time.Time) *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.SetNextRetryAt(v)
	})
}

// UpdateNextRetryAt sets the "next_retry_at" field to the value that was provided on create.
func (u *FederationUsageCursorUpsertBulk) UpdateNextRetryAt() *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.UpdateNextRetryAt()
	})
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (u *FederationUsageCursorUpsertBulk) ClearNextRetryAt() *FederationUsageCursorUpsertBulk {
	return u.Update(func(s *FederationUsageCursorUpsert) {
		s.ClearNextRetryAt()
	})
}

// Exec executes the query.
func (u *FederationUsageCursorUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FederationUsageCursorCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FederationUsageCursorCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FederationUsageCursorUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
