// Code generated by ent, DO NOT EDIT.

package federationusagecursor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/LuckyKuang/sub2api-plus/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldUpdatedAt, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldScope, v))
}

// LastDeliveredID applies equality check predicate on the "last_delivered_id" field. It's identical to LastDeliveredIDEQ.
func LastDeliveredID(v int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldLastDeliveredID, v))
}

// Attempts applies equality check predicate on the "attempts" field. It's identical to AttemptsEQ.
func Attempts(v int) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldAttempts, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldLastError, v))
}

// NextRetryAt applies equality check predicate on the "next_retry_at" field. It's identical to NextRetryAtEQ.
func NextRetryAt(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldNextRetryAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLTE(FieldUpdatedAt, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldContainsFold(FieldScope, v))
}

// LastDeliveredIDEQ applies the EQ predicate on the "last_delivered_id" field.
func LastDeliveredIDEQ(v int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldLastDeliveredID, v))
}

// LastDeliveredIDNEQ applies the NEQ predicate on the "last_delivered_id" field.
func LastDeliveredIDNEQ(v int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNEQ(FieldLastDeliveredID, v))
}

// LastDeliveredIDIn applies the In predicate on the "last_delivered_id" field.
func LastDeliveredIDIn(vs ...int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldIn(FieldLastDeliveredID, vs...))
}

// LastDeliveredIDNotIn applies the NotIn predicate on the "last_delivered_id" field.
func LastDeliveredIDNotIn(vs ...int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNotIn(FieldLastDeliveredID, vs...))
}

// LastDeliveredIDGT applies the GT predicate on the "last_delivered_id" field.
func LastDeliveredIDGT(v int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGT(FieldLastDeliveredID, v))
}

// LastDeliveredIDGTE applies the GTE predicate on the "last_delivered_id" field.
func LastDeliveredIDGTE(v int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGTE(FieldLastDeliveredID, v))
}

// LastDeliveredIDLT applies the LT predicate on the "last_delivered_id" field.
func LastDeliveredIDLT(v int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLT(FieldLastDeliveredID, v))
}

// LastDeliveredIDLTE applies the LTE predicate on the "last_delivered_id" field.
func LastDeliveredIDLTE(v int64) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLTE(FieldLastDeliveredID, v))
}

// AttemptsEQ applies the EQ predicate on the "attempts" field.
func AttemptsEQ(v int) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldAttempts, v))
}

// AttemptsNEQ applies the NEQ predicate on the "attempts" field.
func AttemptsNEQ(v int) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNEQ(FieldAttempts, v))
}

// AttemptsIn applies the In predicate on the "attempts" field.
func AttemptsIn(vs ...int) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldIn(FieldAttempts, vs...))
}

// AttemptsNotIn applies the NotIn predicate on the "attempts" field.
func AttemptsNotIn(vs ...int) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNotIn(FieldAttempts, vs...))
}

// AttemptsGT applies the GT predicate on the "attempts" field.
func AttemptsGT(v int) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGT(FieldAttempts, v))
}

// AttemptsGTE applies the GTE predicate on the "attempts" field.
func AttemptsGTE(v int) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGTE(FieldAttempts, v))
}

// AttemptsLT applies the LT predicate on the "attempts" field.
func AttemptsLT(v int) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLT(FieldAttempts, v))
}

// AttemptsLTE applies the LTE predicate on the "attempts" field.
func AttemptsLTE(v int) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLTE(FieldAttempts, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldContainsFold(FieldLastError, v))
}

// NextRetryAtEQ applies the EQ predicate on the "next_retry_at" field.
func NextRetryAtEQ(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldEQ(FieldNextRetryAt, v))
}

// NextRetryAtNEQ applies the NEQ predicate on the "next_retry_at" field.
func NextRetryAtNEQ(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNEQ(FieldNextRetryAt, v))
}

// NextRetryAtIn applies the In predicate on the "next_retry_at" field.
func NextRetryAtIn(vs ...time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldIn(FieldNextRetryAt, vs...))
}

// NextRetryAtNotIn applies the NotIn predicate on the "next_retry_at" field.
func NextRetryAtNotIn(vs ...time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNotIn(FieldNextRetryAt, vs...))
}

// NextRetryAtGT applies the GT predicate on the "next_retry_at" field.
func NextRetryAtGT(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGT(FieldNextRetryAt, v))
}

// NextRetryAtGTE applies the GTE predicate on the "next_retry_at" field.
func NextRetryAtGTE(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldGTE(FieldNextRetryAt, v))
}

// NextRetryAtLT applies the LT predicate on the "next_retry_at" field.
func NextRetryAtLT(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLT(FieldNextRetryAt, v))
}

// NextRetryAtLTE applies the LTE predicate on the "next_retry_at" field.
func NextRetryAtLTE(v time.Time) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldLTE(FieldNextRetryAt, v))
}

// NextRetryAtIsNil applies the IsNil predicate on the "next_retry_at" field.
func NextRetryAtIsNil() predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldIsNull(FieldNextRetryAt))
}

// NextRetryAtNotNil applies the NotNil predicate on the "next_retry_at" field.
func NextRetryAtNotNil() predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.FieldNotNull(FieldNextRetryAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FederationUsageCursor) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FederationUsageCursor) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FederationUsageCursor) predicate.FederationUsageCursor {
	return predicate.FederationUsageCursor(sql.NotPredicates(p))
}
